unstable_features = true
use_small_heuristics = "Max"
brace_style = "PreferSameLine"
fn_single_line = true
reorder_impl_items = true
trailing_comma = "Never"
use_field_init_shorthand = true
use_try_shorthand = true
fn_args_density = "Tall"
condense_wildcard_suffixes = true
where_single_line = true
format_strings = true
imports_indent = "Block"
merge_imports = true
struct_lit_single_line = true
max_width = 100